// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib = { n ->
  if (n <= 1) n
  else call(n - 1) + call(n - 2)
}

def f, sum
f = sum = 0
for (n = 1; (f = fib(n)) <= 4_000_000; n++) {
  if (f % 2 == 0) { sum += f }
}
println sum
